# -*- coding: utf-8 -*-
{
    "name": "Chăm sóc khách hàng",
    "version": "1.0",
    "summary": "zen8labs crm module",
    "description": "zen8labs crm module",
    "category": "zen8labs/zen8labs",
    "author": "zen8labs",
    "website": "https://www.zen8labs.com",
    "sequence": 1,
    "depends": [
        "z_web",
        "base_automation",
        "z_appointment",
        "z_partner",
        "z_medical_record",
        "z_invoice",
        "z_combo",
        "helpdesk",
        "cron_visualization",
        "z_zns",
    ],
    "data": [
        "data/ir_cron_data.xml",
        "security/ir.model.access.csv",
        "views/z_crm_task_views.xml",
        "views/z_crm_zns_views.xml",
        "views/z_queue_views.xml",
        "views/z_crm_logs_views.xml",
        "views/res_partner_views.xml",
        "views/menu.xml",
        "views/helpdesk_ticker_views.xml",
        "data/ir_cron_data.xml",
    ],
    "assets": {
        "web.assets_backend": [],
    },
    "auto_install": False,
    "application": False,
    "license": "LGPL-3",
}
