# -*- coding: utf-8 -*-
{
    "name": "Hồ sơ bệnh án phòng khám sản",
    "version": "1.0",
    "summary": "zen8labs obstetric medical record module",
    "description": "zen8labs obstetric medical record module",
    "category": "zen8labs/zen8labs",
    "author": "zen8labs",
    "website": "https://www.zen8labs.com",
    "depends": [
        "z_hr",
        "z_medical_record",
        "amazon_s3_connector",
        "z_partner",
        "z_appointment",
        "z_stock",
        "z_product",
        "z_invoice",
        "web_notify",
        "helpdesk"
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/visit_views.xml",
        "views/gynecological_views.xml",
        "views/non_speculum_gynecological_views.xml",
        "views/post_first_trimester_pregnant_views.xml",
        "views/pre_first_trimester_pregnant_views.xml",
        "views/ultrasound_views.xml",
        "views/general_result_views.xml",
        "views/indicated/gynecological_ultrasound_views.xml",
        "views/indicated/post_first_indicated_views.xml",
        "views/indicated/pre_first_indicated_views.xml",
        "views/examination_views.xml",
        "views/indicated_views.xml",
        "views/ovulation_indicated_views.xml",
        "views/medical_test_views.xml",
        "views/partner_views.xml",
        "views/service_code_view.xml",
        "views/product_views.xml",
        "views/report/obstetric_indicated_view.xml",
        "views/report/general_results_view.xml",
        "views/report/obstetric_form_view.xml",
        "views/report/conclude_result_view.xml",
        "views/invoice_views.xml",
        "views/medical_tips_views.xml",
        "views/full_body_views.xml",
        "views/report/obstetric_tips_view.xml",
        "views/report/conclude_result_view.xml",
        "views/report/obstetric_test_view.xml",
        "views/report/account_move_view.xml",
        "views/indicated/fetal_ultrasound_views.xml",
        "views/stock_views.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "z_obstetric/static/src/scss/*.scss",
            "z_obstetric/static/src/fields/*/*.xml",
            "z_obstetric/static/src/fields/*/*.js",
            "z_obstetric/static/src/js/*.js",
            "z_obstetric/static/src/validators/*.js",
            "z_obstetric/static/src/views/*/*.js",
            "z_obstetric/static/src/views/*/*.xml",
            "z_obstetric/static/src/constants/*.js",
        ],
    },
    "installable": True,
    "license": "LGPL-3",
}
