# -*- coding: utf-8 -*-
{
    "name": "Hoá đơn",
    "version": "1.0",
    "summary": "zen8labs invoice module",
    "description": "zen8labs invoice module",
    "category": "zen8labs/zen8labs",
    "author": "zen8labs",
    "website": "https://www.zen8labs.com",
    "sequence": 10,
    "depends": [
        "account",
        "z_partner",
        "z_product",
        "z_web",
        "z_appointment",
        "z_medical_record",
        "z_place",
        "z_combo",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/invoice_data.xml",
        "views/res_config_settings_views.xml",
        "views/invoice_views.xml",
        "views/account_payment_register.xml",
        "views/visit_views.xml",
        "views/place_views.xml",
        "views/res_partner_views.xml",
        "views/account_journal_views.xml",
        "views/purchased_combo_report.xml",
        "views/misa_template_views.xml",
        "wizard/account_move_misa_issuance_views.xml",
        "wizard/account_move_email_wizard_views.xml",
        "wizard/bulk_wizard_views.xml",
        "views/bulk_operation_log_views.xml",
        "report/bulk_operation_log_report.xml",
        "report/account_invoice_template.xml",
        "report/account_invoice_view.xml",
        "wizard/account_move_reversal_views.xml",
        "views/account_payment.xml",
        "report/account_invoice_template.xml",
        "report/account_invoice_view.xml",
        "report/account_payment_view.xml",
    ],
    "installable": True,
    "assets": {
        "web.assets_backend": [
            "z_invoice/static/src/components/*/*.js",
            "z_invoice/static/src/js/*.js",
            "z_invoice/static/src/components/*/*.xml",
            "z_invoice/static/src/scss/*.scss",
            "z_invoice/static/src/css/*.css",
        ]
    },
    "license": "LGPL-3",
    "external_dependencies": {
        "python": ["requests"],
    },
}
