# -*- coding: utf-8 -*-
{
    "name": "Base",
    "version": "1.0",
    "summary": "zen8labs i-base module",
    "description": "zen8labs i-base module",
    "category": "zen8labs/zen8labs",
    "author": "zen8labs",
    "website": "https://www.zen8labs.com",
    "sequence": 10,
    "depends": [
        "z_web",
        "z_product",
        "z_combo",
        "z_stock",
        "z_invoice",
        "z_partner",
        "z_hr",
        "z_appointment",
        "z_medical_record",
        "z_crm",
        "z_zns",
        "report_pdf_options",
    ],
    "data": [],
    "assets": {},
    "application": True,
    "license": "LGPL-3",
}
