# -*- coding: utf-8 -*-
{
    "name": "Hồ sơ bệnh án phòng khám mắt",
    "version": "1.0",
    "summary": "zen8labs ophthalmology medical record module",
    "description": "zen8labs ophthalmology medical record module",
    "category": "zen8labs/zen8labs",
    "author": "zen8labs",
    "website": "https://www.zen8labs.com",
    "depends": [
        "z_hr",
        "z_appointment",
        "z_medical_record",
        "z_invoice",
        "z_glass_order",
        "z_stock",
        "z_hr",
        "z_place",
        "z_partner",
        "z_crm",
        "z_product",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/cls_views.xml",
        "views/comprehensive_views.xml",
        "views/lens_views.xml",
        "views/re_lens_views.xml",
        "views/vision_views.xml",
        "views/binocular_vision_views.xml",
        "views/visit_views.xml",
        "views/res_partner_views.xml",
        "views/helpdesk_ticker_views.xml",
        "views/account_invoice_report_view.xml",
        "views/ophthalmology_menu_views.xml",
        "views/product_views.xml",
        "views/report/comprehensive_views.xml",
        "views/report/comprehensive_template.xml",
        "views/report/lens_template.xml",
        "views/report/lens_views.xml",
        "views/report/re_lens_views.xml",
        "views/report/re_lens_template.xml",
        "views/report/vision_views.xml",
        "views/report/vision_template.xml",
        "views/report/binocular_vision_views.xml",
        "views/report/binocular_vision_template.xml",
        "views/invoice_views.xml",
        "views/research_views.xml",
        "views/menu.xml",
        "views/research_views.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "z_ophthalmology/static/src/scss/*.scss",
            "z_ophthalmology/static/src/fields/*/*.xml",
            "z_ophthalmology/static/src/fields/*/*.js",
            "z_ophthalmology/static/src/view/customer_form.xml",
        ],
    },
    "installable": True,
    "license": "LGPL-3",
}
